#
#  ____       _   _            _   _
# |  _ \     | | | |          | \ | |
# | |_) | ___| |_| |_ ___ _ __|  \| | __ ___   __
# |  _ < / _ \ __| __/ _ \ '__| . ` |/ _` \ \ / /
# | |_) |  __/ |_| ||  __/ |  | |\  | (_| |\ V /
# |____/ \___|\__|\__\___|_|  |_| \_|\__,_| \_/
#
# BetterNavigating V${project.version}

# Enabling public or private location savings
privateWayPoints : true

# Maximum Waypoints per folder
maximumWaypoints : 10

# Displaying welcome message
welcomeMessage : true

# BossBar Navigating style
BossBar : 2

# Distance to waypoint before ending navigation
Distance: 5





