name: BetterNav
main: com.company.betternav.BetterNav
version: ${project.version}
author: [Thomas Verschoor, Dieter Nuytemans]
api-version: 1.16
commands:
  bn:
    description: show explanation of commands
    usage: /<command>
    aliases: [help]

  getlocation:
    description: show location of the player
    usage: :/<command>
    aliases: [toggle]

  savelocation:
    description: save location on map
    usage: :/<command>
    aliases: [save]

  showlocations:
    description: show locations saved
    usage: :/<command>
    aliases: [showpossiblelocations]


  showcoordinates:
    description: show coordinates of saved location
    usage: :/<command>
    aliases: [getcoordinates]

  nav:
    description: navigate to
    usage: :/<command>
    aliases: [nav,goto]

  del:
    description: delete
    usage: :/<command>

  navplayer:
    description: navigate to player
    usage: :/<command>

  stop:
    description: stop navigation
    usage: :/<command>






