#
#  ____       _   _            _   _
# |  _ \     | | | |          | \ | |
# | |_) | ___| |_| |_ ___ _ __|  \| | __ ___   __
# |  _ < / _ \ __| __/ _ \ '__| . ` |/ _` \ \ / /
# | |_) |  __/ |_| ||  __/ |  | |\  | (_| |\ V /
# |____/ \___|\__|\__\___|_|  |_| \_|\__,_| \_/
#
# BetterNavigating V${project.version}

# Enabling public or private location savings
privateWayPoints : {privateWayPoints}

# Maximum Waypoints per folder
maximumWaypoints : {maximumWaypoints}

# Displaying welcome message
welcomeMessage : {welcomeMessage}

# BossBar Navigating style
BossBar : {BossBar}

# BossBar coloring
BossBar_color: {BossBar_color}

# Distance to waypoint before ending navigation
Distance : {Distance}

# Whether or not animations are enabled
enableAnimations : {enableAnimations}

# language
language : {language}

# check for height
height_check: {height_check}





